### ISSUE TITLE
Using right-angled with old versions of angular 2 with new version of right-angled

### ISSUE THREAD

**Issue by denismaster** [eastbanctechru/right-angled#83]
Hello, we want to use this library, but it requires a new versions of Angular 2 npm packages, such as 2.4 and  higher.
But in our project the max version we can use is 2.2.4. Newer versions aren't working.
How can we do that without upgrading angular packages?
We want this to save state of filters, sorting and paging like in tutorial.
And if we can't use old versions, how we can persist state in beta.1 version?

**Comment by fshchudlo** [comment]
Hello.

Due to [this issue](https://github.com/angular/angular/issues/11606) the minimal required version of `angular` is 2.3.0. Otherwise the latest `right-angled` version will not work in AOT mode.

To use persistence with beta.1, you can manually inject your state service implemetations into your end up components and register them in [onListInit](https://eastbanctechru.github.io/right-angled-demo/list-controls#on-list-init) event handler with the folowwing snippet:
```typescript
onListInit(list: RtList): void {
   list.registerStateService(this.localStorageStateService, this.sessionStorageStateService, this.queryStringStateService);
}
```
Additionally, you can write custom directives [like this](https://github.com/eastbanctechru/right-angled-demo/blob/36fcc3a1fe6efbcfc9babfdd3c3ac07481134073/src/app/shared/state-services/serialize-to-local-storage.directive.ts) to reduce amount of registration code and use it in your templates.

Unfortunatelly, this is the only way to use persistence in 2.2.4 since registration via `providers` property of parent component doesn't work in `angular` 2.2.4.

Hope this helps.
