### ISSUE TITLE
Wrong context ('this') for rtList function invocation

### ISSUE THREAD

**Issue by GerrAlt12** [eastbanctechru/right-angled#84]
Hello!
I use angular AoT compiler for build my project and rollupjs for bundle it. I try to perform basic scenario from tutorial
```html
...
        <table [rtList]="getList" #wholeList="rtList">
            <tbody>
                <tr
                    *ngFor="let item of wholeList.items; let i = index"
                    [ngClass]="{
                        'jmc_hide': !isRowVisible(item)
                    }"
                    [ngSwitch]="item.mcs_id > 0"
                >
                    <td *ngSwitchCase="false" colspan="2" >
                        <div *ngIf="!isEmptyGroup(i)" [ngSwitch]="currentOpenedGroup === item['specs_id']">
                            <md-icon (click)="currentOpenedGroup = item['specs_id']" *ngSwitchCase="false" >expand_more</md-icon>
                            <md-icon (click)="currentOpenedGroup = null" *ngSwitchCase="true" >expand_less</md-icon>
                        </div>
                        {{item.specs_name}}
                    </td>
                </tr>
            </tbody>
        </table>
...
```

```typescript
@Component({
  moduleId: module.id,
  selector: 'my-list-items',
  templateUrl: 'app.component.html',
  styleUrls: ['default.css']
})
export class AppComponent {
  constructor(private myResource:MyResource) { }
...
  getList() {
    return this.myResource.query({active: true}).$observable;
  }
...
}
```

All compiled successfully, but when I deploy bundle and visit page I saw error:
"EXCEPTION: Cannot read property 'query' of undefined"

When I start debugging, I found that "this" in function "getList" points to RTList.

I do something wrong?

**Comment by fshchudlo** [comment]
Hello!
The key thing is how your `getList` function defined. 
`rtList` directive can't determine correct context by itself because all that `rtList` gets is reference to the function. 
There is two possible ways to fix this:
1. Define `getList` as arrow funtion instead of a regular method. This approach is taken in `right-angled` demos:
```typescript
getList = () => {
    return this.airportsService.getAirportsList(request);
  }
```

2. Use [Function.prototype.bind](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Function/bind) to bind the context of a function manually.

Hope this helps.
