### ISSUE TITLE
Two lists on same page

### ISSUE THREAD

**Issue by aradosz79** [eastbanctechru/right-angled#97]
I wanted to put two list on same page but failed to achieve this. 

I see there is some parameter  #list="rtList" in the table template but when i change it to some other value
i get following error:

````
Unhandled Promise rejection: Template parse errors:
There is no directive with "exportAs" set to "rList" ("<div class="table-responsive">
  <table class="table table-striped" [rtList]="getHeaders" [ERROR ->]#list="rList">
```
Is there any way to use your component multiple times on same page?

**Comment by fshchudlo** [comment]
Hello.

Sure, you can put two lists on same page. 

As I can see from error message you provide, you've try to change right part of variable assignment from `rtList` to `rList`. But you need to change left part of assignment since right part is the name of directive, not the variable name.

You can view [this template](https://github.com/eastbanctechru/right-angled-demo/blob/master/src/app/quick-tour/use-paging/use-paging.component.html) from demo application as working sample of [two lists placed in one template](https://eastbanctechru.github.io/right-angled-demo/quick-tour#use-paging).
